apiVersion: v1
kind: Service
metadata:
  name: bank-app
  namespace: bank-system
  labels:
    app: bank-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
  selector:
    app: bank-app

