apiVersion: v1
kind: Secret
metadata:
  name: bank-secrets
  namespace: bank-system
type: Opaque
stringData:
  # Database credentials
  db-name: "neondb"
  db-user: "neondb_owner"
  db-password: "npg_W9IOFPx0EusK"
  
  # RabbitMQ credentials
  rabbitmq-username: "guest"
  rabbitmq-password: "eW91ci1zdXBlci1zZWNyZXQta2V5LWhlcmU=" # ОБОВ'ЯЗКОВО змініть!
  
  # JWT Secret (Base64 encoded) - має бути мінімум 32 байти (256 біт) для HS256
  jwt-secret: "c2VjdXJlLXNlY3JldC1rZXktMzItYnl0ZXMtc2hvdWxkLWJlLWJhc2U2NA==" # Base64-encoded 32-byte secret

