apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-immediate
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  fsType: ext4
volumeBindingMode: Immediate  # Зміна з WaitForFirstConsumer на Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete

