spring:
  application:
    name: hm1
  profiles:
    active: local # Активний локальний профіль
  sql:
    init:
      mode: always # SQL-скрипти (schema.sql та data.sql) автоматично виконуються під час запуску
security:
  jwt:
    secret: "c2VjdXJlLXNlY3JldC1rZXktMzItYnl0ZXMtc2hvdWxkLWJlLWJhc2U2NA==" # Base64-encoded секрет для JWT
    expirationMillis: 3600000 # Термін дії токена (1 година)
server:
  port: 9000 # Порт бекенда

---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb # URL бази даних PostgreSQL
    username: bankuser # Ім'я користувача бази
    password: bankpass # Пароль до бази
    driver-class-name: org.postgresql.Driver # Драйвер JDBC PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update # Автоматичне оновлення/створення таблиць
    show-sql: true # Виводити SQL-запити у лог
    properties:
      hibernate:
        enable_lazy_load_no_trans: true # Дозволити lazy loading поза транзакцією
  jackson:
    serialization:
      fail-on-empty-beans: false # Не падати на порожніх beans
  hikari:
    maximum-pool-size: 10 # Максимальна кількість підключень до бази